name: Deploy Gstaldergeist

on:
  push:
    branches:
      - main # Triggers only when you push to this branch
  workflow_dispatch: # Enables manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Start Podman Socket
        run: |
          sudo systemctl start podman.socket
          systemctl status podman.socket
      - name: Podman build and tag
        run: |
          podman build -t gstaldergeist:latest .
      - name: push to registry
        run: |
          podman login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ secrets.REGISTRY_URL }}
          podman tag gstaldergeist:latest ${{ secrets.REGISTRY_URL }}/gstaldergeist:latest
          podman push ${{ secrets.REGISTRY_URL }}/gstaldergeist:latest
