name: Deploy Gstaldergeist

on:
  push:
    branches:
      - main # Triggers only when you push to this branch
  workflow_dispatch: # Enables manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Start Podman Socket
        run: |
          sudo systemctl start podman.socket
          systemctl status podman.socket
      - name: Check Podman Version
        run: podman --version
