name: Deploy Gstaldergeist with Podman

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Podman
        uses: redhat-actions/podman-build@v2
        with:
          command: version # Verify Podman installation

      - name: Login to GitHub Container Registry
        run: |
          podman login -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Build and push container image
        uses: redhat-actions/podman-build@v2
        with:
          tags: ghcr.io/${{ github.repository }}:latest
          push: true
          build_args: |
            BUILDKIT_INLINE_CACHE=1 # Optional: Enable BuildKit inline cache

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Likely much shorter now
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/ansible-deploy
            ansible-playbook deploy_podman.yml
