name: Deploy Gstaldergeist Testing
permissions:
  packages: write
  contents: read
on:
  push:
    branches:
      - main # Triggers only when you push to this branch
  workflow_dispatch: # Enables manual trigger

jobs:
  push-to-registry:
    runs-on: ubuntu-latest
    environment: TESTING
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Start Podman Socket
        run: |
          sudo systemctl start podman.socket
          systemctl status podman.socket
      - name: Login to GitHub Container Registry
        run: |
          podman login -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - name: Podman build and tag
        run: |
          podman build \
          -t ghcr.io/${{ github.repository_owner }}/gstaldergeist:nightly \
          --layers \
          --cache-from=ghcr.io/${{ github.repository_owner }}/gstaldergeist:nightly \
          --cache-to=ghcr.io/${{ github.repository_owner }}/gstaldergeist:nightly \
          .
      - name: push to registry
        run: |
          podman push ghcr.io/${{ github.repository_owner }}/gstaldergeist:${{ github.sha }}
          podman push ghcr.io/${{ github.repository_owner }}/gstaldergeist:nightly
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install Ansible
        run: |
          pip install ansible
      - name: Setup SSH Agent and Add Key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_SSH_KEY }}
      - name: Add Remote Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.ANSIBLE_HOST_IP }} >> ~/.ssh/known_hosts

      - name: Generate Ansible Vars File
        run: |
          CONFIG_PATH=./group_vars/testing.yml
          echo "ansible_host: ${{ secrets.ANSIBLE_HOST_IP }}" >> $CONFIG_PATH
          echo "ansible_user: ${{ secrets.ANSIBLE_USER }}" >> $CONFIG_PATH
        working-directory: ./ansible

      - name: Generate Env File
        env:
          ALL_SECRETS_JSON: ${{ toJson(secrets) }}
        run: |
          CONFIG_PATH=".env"
          EXCLUDE_PREFIX="ANSIBLE_"
          echo "$ALL_SECRETS_JSON" | \
          jq -r '
            to_entries[]
            | select(.key | startswith("'"$EXCLUDE_PREFIX"'") | not)
            | "\(.key)=\(.value)"
          ' > "$CONFIG_PATH"
        working-directory: ./ansible

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini playbook.yml -l testing
        working-directory: ./ansible
