name: Hello World

on:
  workflow_dispatch:

jobs:
  hello:
    environment: PRODUCTION
    runs-on: ubuntu-latest
    steps:
      - run: echo -n "ansible_user ${ANSIBLE_HOST_IP}" | base64
        env:
          ANSIBLE_HOST_IP: ${{ secrets.ANSIBLE_HOST_IP }}
