name: Hello World

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:
      - run: echo -n "ansible_user ${ANSIBLE_USER}" | base64
        env:
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
